"""
api.py — FastAPI server exposing the Bug Triage Agent as a REST API.

Run:
    uvicorn api:app --reload --port 8000

Endpoints:
    POST /triage         — Run the full triage agent on a bug report
    GET  /health         — Health check
"""

from dotenv import load_dotenv
load_dotenv()

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from typing import Optional

from agent import agent

app = FastAPI(
    title="Bug Triage Agent API",
    description="LangGraph-powered bug triage and root-cause analysis agent",
    version="1.0.0",
)


# ── Request / Response models ─────────────────────────────────────────────────

class TriageRequest(BaseModel):
    bug_report: str = Field(
        ...,
        description="The raw bug report text",
        example="API response time increased 300% after deploying v2.3.1. Redis timeouts in logs.",
    )


class TriageResponse(BaseModel):
    report: str = Field(..., description="Structured Markdown incident report")
    analysis: str = Field(..., description="Root-cause analysis produced by the analyzer node")
    iterations: int = Field(..., description="Number of retrieval loops performed")
    diagnostic_questions: list[str] = Field(..., description="Questions generated by the planner node")


# ── Routes ────────────────────────────────────────────────────────────────────

@app.get("/health")
def health():
    return {"status": "ok"}


@app.post("/triage", response_model=TriageResponse)
def triage(request: TriageRequest):
    """
    Run the full LangGraph bug triage agent on the provided bug report.

    The agent will:
    1. Plan diagnostic questions
    2. Retrieve relevant past incidents from the vector store (RAG)
    3. Analyze root cause
    4. Validate analysis quality (retry loop if insufficient)
    5. Generate a structured incident report
    """
    if not request.bug_report.strip():
        raise HTTPException(status_code=400, detail="bug_report cannot be empty")

    initial_state = {
        "bug_report": request.bug_report.strip(),
        "diagnostic_questions": [],
        "retrieved_contexts": [],
        "analysis": "",
        "is_sufficient": False,
        "iterations": 0,
        "report": None,
    }

    try:
        final_state = agent.invoke(initial_state)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Agent error: {str(e)}")

    return TriageResponse(
        report=final_state["report"],
        analysis=final_state["analysis"],
        iterations=final_state["iterations"],
        diagnostic_questions=final_state["diagnostic_questions"],
    )
